# Generated by Django 4.0.dev20210622105104 on 2021-06-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlUnderInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic_name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200)),
                ('regular_expression', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('requests_successfully', models.IntegerField(default=0)),
                ('requests_failed', models.IntegerField(default=0)),
                ('requests_warning', models.IntegerField(default=0)),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_start_time', models.DateField()),
                ('request_end_time', models.DateField(null=True)),
                ('head', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=800, null=True)),
                ('info', models.CharField(max_length=200, null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('url_under_investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_analysers.urlunderinvestigation')),
            ],
        ),
    ]
