# Generated by Django 4.0.dev20210622105104 on 2021-07-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_site_availability",
            "0003_alter_singlecheckrequest_completed_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="website",
            name="favourite",
        ),
    ]
