# Generated by Django 4.0.dev20210622105104 on 2021-07-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_site_availability",
            "0006_alter_singlecheckrequest_pattern_regular_expression_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlecheckrequest",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="website",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="websitecheckrequest",
            name="completed_at",
        ),
    ]
