# Generated by Django 3.2.7 on 2021-09-16 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_site_availability",
            "0007_remove_singlecheckrequest_completed_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlecheckrequest",
            name="regular_expression",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[django.core.validators.RegexValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="websitecheckrequest",
            name="regular_expression",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[django.core.validators.RegexValidator()],
            ),
        ),
    ]
